name: Delete remote branch
description: >-
  Useful to delete branch in a remote repository
inputs:
  destination-github-username:
    description: Name of the destination username/organization
    required: true
  destination-repository-name:
    description: Destination repository
    required: true
  user-email:
    description: Email for the git commit
    required: true
  github-server:
    description: 'Github server'
    default: 'github.com'
    required: false
  user-name:
    description: >-
      [Optional] Name for the git commit. Defaults to the destination
      username/organization name
    required: false
    default: ''
  destination-repository-username:
    description: '[Optional] Username/organization for the destination repository'
    required: false
    default: ''
  target-branch:
    description: >-
      [Optional] set target branch name for the destination repository. Defaults
      to "main"
    default: main
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.destination-github-username }}'
    - '${{ inputs.destination-repository-name }}'
    - '${{ inputs.github-server }}'
    - '${{ inputs.user-email }}'
    - '${{ inputs.user-name }}'
    - '${{ inputs.destination-repository-username }}'
    - '${{ inputs.target-branch }}'

branding:
  icon: git-commit
  color: green
